PROBALITIES = [0.8, 0.2]
LAMBDAS = [0.5, 1.2]

NUM_PRIORITIES = 4
NUM_PROCESS = 4
NUM_PROCESSORS = 2
SERVICE_TIME_TASK = 3
NUM_TASKS = 10
TIME_STEP = 0.1
COEFF_ROUND = 1
TIME_SIMULATION = 10.0
MAX_SIZE_BUFFER = 5

ARRIVAL = 'arrival'
NEW_WORK = 'new_work'
INTERRUPT = 'interrupt'
RUNNING = 'RUNNING'
SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'