PROBALITIES = [0.8, 0.2]
LAMBDAS = [0.5, 1.2]

NUM_PRIORITIES = 4
NUM_PROCESS = 4
PROCESSORS = 2
TIME_QUANTUM = 5
NUM_TASKS = 1000
TIME_STEP = 0.1
COEFF_ROUND = 1
MAX_RUN_TIME = 10.0
MAX_SIZE_BUFFER = 10

ARRIVAL = 'arrival'
NEW_WORK = 'new_work'